language: objective-c
osx_image: xcode7.1
script:
- set -o pipefail
- xcodebuild -workspace "DarkLightning.xcworkspace" -scheme "DarkLightning-OSX" -sdk "macosx10.11" -destination "arch=x86_64" -configuration Debug ONLY_ACTIVE_ARCH=NO test