language: objective-c
osx_image: xcode7.2
before_install:
    - brew update
    - brew upgrade xctool
script:
  - xctool -project DarkLightning.xcodeproj -scheme DarkLightning-OSX build test -sdk macosx GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)